### ISSUE TITLE
Notify slack channel on new posts

### ISSUE THREAD

**Issue by Dunklas** [DeviesDevelopment/blog#28]
Setup automatic slack notifications to e.g. #general on new posts

**Comment by fredrik-mile-wcar** [comment]
My first idea was to write a workflow for it but it is probably easier to: 

1. Add RSS feed to the blog. 
2. Configure slack channel to subscribe to the RSS feed.

**Comment by Dunklas** [comment]
Seems like we have an RSS feed for posts by default? https://deviesdevelopment.github.io/blog/posts/index.xml

**Comment by mile95** [comment]
I've made sure that devies-development channel and github-review channel subscribe to https://deviesdevelopment.github.io/blog/posts/index.xml

We can close this issue if we see that the next post gets posted in the above mention channels.

**Comment by Dunklas** [comment]
Slack channel #general is now successfully notified on new posts! Closing this issue.
